name: Linux Build

on:
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  #SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: release_x64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup premake
      uses: abel0b/setup-premake@master
      
    - name: Setup Environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install gcc-multilib
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
      
    - name: Run Premake
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: premake5 gmake2
    
    - name: make help
      run: make help

    - name: make
      run: make config=${{env.BUILD_CONFIGURATION}}
      
    - uses: actions/upload-artifact@v2
      with:
        name: lunar-artifact
        path: |
          game/
          
    - uses: actions/upload-artifact@v2
      with:
        name: lunar-artifact
        path: |
          bin/${{env.BUILD_CONFIGURATION}}/*
